# Generated by Django 5.2 on 2025-05-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_exchangerequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exchangerequest',
            table='exchange_exchangerequest',
        ),
    ]
